### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-W09-C3/main#86]
I reviewed your docs by mistake. :-p
Anyway, here's my feedback:
# Developer Guide
- Navigability from TimeInterval to Recurrance seems odd. Give multiplicities for Length etc. 
  ![image](https://cloud.githubusercontent.com/assets/1673303/19547966/0e257686-96ce-11e6-90f1-008843cc19f2.png)
- You mention UrlUtilTest, but do you even need the UrlUtil class?
- There are some `{more to be added}` comments that need to be removed.
- The product comparison table at the bottom is not in a very author-friendly form (in the markdown file).
- Suggested additions:
  - Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way. 
  - Similarly, you can explain other interesting design decisions you made.
# User Guide
- Does the UI sketch match the direction you are heading?
- Why is this info relevant to the user? BTW, this screenshot is from another team. You seem to have exact same phrase.
  ![image](https://cloud.githubusercontent.com/assets/1673303/19547661/2d8b704a-96cc-11e6-8c89-bf7b418f2b60.png) 
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- Put all acknowledgements in the README page. BTW, you are supposed to acknowledge the use of sample code from AddressBook-Level4

**Comment by jamos-tay** [comment]
Hi @damithc ,

Thanks for taking the time to review our docs :-P

Regarding the similarity, we don't know why they're so similar, but we definitely wrote that paragraph ourselves.

In fact, that paragraph was committed to our repo 2 days earlier than theirs:

![image](http://puu.sh/rPf5c/5f57ff0c73.png) 

We've never discussed this with them so we're not sure what happened.

**Comment by antonong94** [comment]
Hi @damithc, as i am not too sure of what to include in the user guide. I take reference to find any points that i can improve on. The other team has nothing to do with this. I apologize for this and will take sole responsibility for anything that happens. Thank you.

**Comment by damithc** [comment]
It's fine to adopt stuff from other teams or get inspired by what others are doing, as long as you give due credit.

**Comment by antonong94** [comment]
Ok thanks! i will take note of this. Sorry for any inconvenience caused.
